### ISSUE TITLE
How to change viewController on some tab?

### ISSUE THREAD

**Issue by LunevNF** [ezescaruli/ESTabBarController#12]
At app load, I succesfully init ESTabBarController.
Init controllers with:
`questionsVC *questions = [self.storyboard instantiateViewControllerWithIdentifier:@"questionsVCStory"];`
`[tabBarController_ setViewController:questions atIndex:1];`
When I autorize at someone web-service, I need to change installed viewController to another viewController.

I try to change like this:
`
newsVC *news = [self.storyboard instantiateViewControllerWithIdentifier:@"newsVCStory"];
[tabBarController_ setViewController:news
                                 atIndex:1];
`
It's worked, but If I go from 1 tab to 3 tab, and will push some viewController (prepareForSegue...) and after that tap on "back", ESTabBarController move me on first tab, where I change before "questionsVC" on "newsVC ". (There I see "newsVC"). 
So, `[tabBarController_ setViewController:news atIndex:1];` worked, but why tabBarController move me on tab, where I change viewController, after popViewController from all other tabs?
How to change viewController at index normaly?

**Comment by lukitnev** [comment]
I see, that when I pop view controller on 2,3,4 tab's, worked this method:
`(void)moveToControllerAtIndex:(NSInteger)index animated:(BOOL)animated;`
Where index is 1 = index, where I was change questionsVC to newsVC; 
It's strange, because, when we tap on some tab, index must change to tapped tab and after pop view not change.

**Comment by LunevNF** [comment]
I found place, where I switch current tab.
In questionVC at viewDidAppear I write this:
`[appD.tabBarController_ setViewController:appD.msgsList
                                          atIndex:2];`
`[_tabBarController_ setSelectedIndex:1 animated:NO];`
`[_tabBarController_ setSelectedIndex:2 animated:NO];`
I write this for change questionsVC to newsVC.

But WHY viewDidAppear called always, when I call popView at different tabs?
So, I was change questionsVC to newsVC, but viewDidAppear at questionsVC always calling. What me do?

**Comment by LunevNF** [comment]
I solved this issue. I don't know WHY, but it works. Maybe, when we change one controller to another and at this moment we stay on tab, where we change controller, old (changed) controller saved in memory with callback.

If you want to change one controller to another at oppened tab in realtime, you must do this(selected index before changes is 2):
`[_tabBarController_ setSelectedIndex:1 animated:NO];`
`[appD.tabBarController_ setViewController:appD.msgsList atIndex:2];`
`[_tabBarController_ setSelectedIndex:2 animated:NO];`
So, you must change selected index on other before changes with controller. After that return selected index to old. Changes accept.

**Comment by ezescaruli** [comment]
@lukitnev Good catch.

I think what is happening is that, when you set a view controller in a tab where there is already one, then the previous view controller is not being removed from the view controllers hierarchy. Therefore, `UIViewController` methods still get called on it.

I'll add a fix for this.

**Comment by ezescaruli** [comment]
@lukitnev I have merged the fix into `master`. Now you should be able to set a view controller to any index (event o the selected one) without issues.

Would you mind taking a look when you have a chance? Thanks!

**Comment by LunevNF** [comment]
@ezescaruli thanks for your work. Yes, I will look, when be free. I have a lot of work on this week. :(

**Comment by ezescaruli** [comment]
@lukitnev I'll close the issue. If you still find any issues related with this, let me know :)
