### ISSUE TITLE
Controller should use the correct bundle for loading

### ISSUE THREAD

**Issue by lukeredpath** [ezescaruli/ESTabBarController#2]
If you use this library with CocoaPods and `use_frameworks!`, the pod resources will not be in the main bundle.

Fix: use `bundleForClass:` instead of `nil` for the bundle parameter when loading the XIB.

https://github.com/CocoaPods/CocoaPods/issues/3226

**Comment by ezescaruli** [comment]
@lukeredpath Thanks for pointing out. Fixed in https://github.com/ezescaruli/ESTabBarController/pull/4

This should imply a new version soon ;)
