### ISSUE TITLE
Knowing when I switched to a new Tab

### ISSUE THREAD

**Issue by tonespy** [ezescaruli/ESTabBarController#8]
Is it possible to know when I'm in a new View so I can refresh the page. Cause, I've a tableview that I want to reload and fetch data anytime it's switched to. And I also tried to implement NavigationController so I can push to views and also pop views. So, I did this

```
    tabBarController.setAction({ () -> Void in
        self.navigationController?.popToRootViewControllerAnimated(false)
        }, atIndex: 4)
```

It didn't work at all

**Comment by ezescaruli** [comment]
Hi @tonespy, sorry for the delay on this one.

A solution for refetching your data every time your screen appears, could be doing that in the `viewWillAppear:` / `viewDidAppear:` method of your controller for that screen. They are called when switching to a tab that is showing that controller.

Regarding your navigation controller, I think I didn't quite understood it. Could you show me what is the view controller that you are setting at index `4`? Thanks!

**Comment by tonespy** [comment]
This is a long time back. And, I can't even remember why I asked this question. So, I'm going to close it. But, I knew I ended up removing the Module and writing my own to suite my need
