### ISSUE TITLE
Update bar Icons

### ISSUE THREAD

**Issue by Krystel** [ezescaruli/ESTabBarController#9]
Is there any way to update the bar icons without re-initializing it?
What I mean is that after creating the ESTabBarController instance with its appropriate icon images, at some point in the app i need to switch the order of the icons (RTL - LTR), to achieve that I need to be able to switch the icons.

Thank you :)

**Comment by ezescaruli** [comment]
Hi @Krystel,

At the moment that's not possible. That's an interesting feature though, I think it would mean having a method like:

```
- (void)setTabIcon:(UIImage *)icon atIndex:(NSInteger)index;
```

I might look into this in a future PR, or you can give it a try it if you feel fancy to it ;)

**Comment by Krystel** [comment]
Hi @ezescaruli,

Thanks for the reply..
Yea pretty much..

I'll try to have a look when I can :)
